Basic CLI interface for authorization & user management
robotics-laboratory/inventory pull request #2
Opened 2023-08-01 15:16 UTC by n0rdstar-git

2023-08-01 23:57 UTC, AndBondStyle requested changes

2023-08-01 23:57 UTC, AndBondStyle commented on cli.py
> +    id:int,
Форматирование едет местами, почитай как пользоваться pre-commit и прогони в своей ветке через `pre-commit run -a`

2023-08-01 23:57 UTC, AndBondStyle commented on cli.py
> +        id: int,
Ну такие вещи я тоже не очень одобряю, у питона все-таки достаточно приятный синтаксис и лучше стоит его портить лишними переносами строк

2023-08-01 23:57 UTC, AndBondStyle commented on cli.py
> +        elif(is_admin is False):
- Делать ифы ради того чтобы разные сообщения в консоль выводить это странно
- Булы через is никто не сравнивает

2023-08-01 23:57 UTC, AndBondStyle commented on cli.py
> +        new_full_name: str,
Сигнатура некорректная

2023-08-01 23:57 UTC, AndBondStyle commented on cli.py
> +    with database.transaction():
Кажется, строчки "database = container.database()" и "with database transaction" можно убрать (во всем файле), и ничего не изменится, т.к. все операции которые ты дергаешь атомарные (на уровне бд)

2023-08-01 23:57 UTC, AndBondStyle commented on cli.py
> +        print(f"ID \t Full name \t Telegram ID \t ADMIN")
Табы запрещено использовать). 
Если хочешь чтобы колонки были предсказуемой ширины, либо выравнивание используй (e.g. `f"{var:<20s}`), либо какую-нибудь либу поставь типа tabulate. Главное не табами

2023-08-01 23:57 UTC, AndBondStyle commented on cli.py
> +            print(f"{user.full_name} \t\t {user.is_admin}")
Ещё вывод в консоль немного chaotic evil (местами через logging, местами через print)

2023-08-01 23:57 UTC, AndBondStyle commented on pyproject.toml
> +    options = ["--by-id", "-i"]
Для консистентности с другими командами должно быть `--id`

2023-08-01 23:57 UTC, AndBondStyle commented on pyproject.toml
> +    options = ["--new-full-name", "-n"]
Аналогично

2023-08-01 23:57 UTC, AndBondStyle commented on pyproject.toml
> +    default = false
Кажется здесь не должно быть дефолта

2023-08-01 23:57 UTC, AndBondStyle commented on main.py
> +    #return
Чё-то мусор какой-то

2023-08-01 23:57 UTC, AndBondStyle commented on main.py
> +from inventory import orm
Imported but unused

2023-08-04 15:13 UTC, n0rdstar-git commented on cli.py
> +        elif(is_admin is False):
Хз, я просто хочу чтобы в явном виде писалось, когда ты что-то делаешь с определённым пользователем. Я бы скорее сказал, что присвоение в обоих ветвях это странно.

2023-08-04 15:23 UTC, n0rdstar-git commented on main.py
> +    #return
Ты про принт настроек? Остальное вроде всё по делу.

2023-08-04 17:40 UTC, n0rdstar-git commented on pyproject.toml
> +    default = false
Либо я убираю тип булеан (установка булеана подразумевает то, что он превращается в флаг с default значением true, которое применяется, если его не передать и инвертируется, если его передать) и мы начинаем писать вещи вида `-a True` и `-a false` в явном виде каждый раз, либо так

2023-08-04 17:41 UTC, n0rdstar-git commented on cli.py
> +        print(f"ID \t Full name \t Telegram ID \t ADMIN")
Вбросил f строки + строку с пробелами для хединга таблички, не хочу ещё одну зависимость подключать. Хотя могу использовать любое, на что укажешь, выбор за тобой

2023-08-05 22:07 UTC, AndBondStyle approved these changes

2023-08-08 15:03 UTC, merged